<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <!--Avalonia doesen't support TrimMode=link currently,but we are working on that https://github.com/AvaloniaUI/Avalonia/issues/6892 -->
    <TrimMode>copyused</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaXaml Remove="Models\**" />
    <AvaloniaXaml Remove="ViewModels\**" />
    <Compile Remove="Models\**" />
    <Compile Remove="ViewModels\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="Models\**" />
    <None Remove="ViewModels\**" />
    <None Remove=".gitignore" />
  </ItemGroup>
  <ItemGroup>
    <!--This helps with theme dll-s trimming.
	If you will publish your application in self-contained mode with p:PublishTrimmed=true and it will use Fluent theme Default theme will be trimmed from the output and vice versa.
	https://github.com/AvaloniaUI/Avalonia/issues/5593 -->
    <TrimmableAssembly Include="Avalonia.Themes.Fluent" />
    <TrimmableAssembly Include="Avalonia.Themes.Default" />
  </ItemGroup>
  <ItemGroup>
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Autofac" Version="8.2.1" />
    <PackageReference Include="Avalonia" Version="11.2.7" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.7" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.7" />
    <PackageReference Include="Griffin.Container" Version="1.1.9" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.3.1" />
    <PackageReference Include="Splat" Version="15.3.1" />
    <PackageReference Include="Splat.Autofac" Version="15.3.1" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IPsPeek.Lib\IpsPeek.Lib.csproj" />
    <ProjectReference Include="..\IpsPeek.UI\IpsPeek.UI.csproj" />
  </ItemGroup>
</Project>
