<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="20.2.45" />
    <PackageReference Include="Splat" Version="15.3.1" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.13" />
  </ItemGroup>

</Project>
