//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpsPeek {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IpsPeek.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About IPS Peek.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Peek Home.
        /// </summary>
        internal static string ApplicationHome {
            get {
                return ResourceManager.GetString("ApplicationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Version {1}..
        /// </summary>
        internal static string ApplicationInformation {
            get {
                return ResourceManager.GetString("ApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block: {0:X} ({0}) - {1:X} ({1}).
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col: {0}.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Hex.
        /// </summary>
        internal static string CopyHex {
            get {
                return ResourceManager.GetString("CopyHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Row.
        /// </summary>
        internal static string CopyRow {
            get {
                return ResourceManager.GetString("CopyRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View.
        /// </summary>
        internal static string DataView {
            get {
                return ResourceManager.GetString("DataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Peek is a tool that allows you to look inside of IPS (International Patching System) patches..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorFileLoadFailed {
            get {
                return ResourceManager.GetString("ErrorFileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File: {0}.
        /// </summary>
        internal static string FileInformation {
            get {
                return ResourceManager.GetString("FileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Files (*.ips)|*.ips.
        /// </summary>
        internal static string FilterIpsFiles {
            get {
                return ResourceManager.GetString("FilterIpsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt.
        /// </summary>
        internal static string FilterTextFiles {
            get {
                return ResourceManager.GetString("FilterTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        internal static string FindEllipses {
            get {
                return ResourceManager.GetString("FindEllipses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        internal static string FindPrevious {
            get {
                return ResourceManager.GetString("FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows: {0:X} ({0}), Patches: {1:X} ({1}), Modified: {2:X} ({2}).
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto.
        /// </summary>
        internal static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Offset.
        /// </summary>
        internal static string GoToOffset {
            get {
                return ResourceManager.GetString("GoToOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Offset....
        /// </summary>
        internal static string GoToOffsetEllipses {
            get {
                return ResourceManager.GetString("GoToOffsetEllipses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Row....
        /// </summary>
        internal static string GoToRow {
            get {
                return ResourceManager.GetString("GoToRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a row number to go to:.
        /// </summary>
        internal static string GoToRowDescription {
            get {
                return ResourceManager.GetString("GoToRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Row.
        /// </summary>
        internal static string GoToRowTitle {
            get {
                return ResourceManager.GetString("GoToRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Contents.
        /// </summary>
        internal static string HelpContents {
            get {
                return ResourceManager.GetString("HelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        internal static string Hexadecimal {
            get {
                return ResourceManager.GetString("Hexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS End.
        /// </summary>
        internal static string IpsEndHeader {
            get {
                return ResourceManager.GetString("IpsEndHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Offset.
        /// </summary>
        internal static string IpsOffsetHeader {
            get {
                return ResourceManager.GetString("IpsOffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Size.
        /// </summary>
        internal static string IpsSizeHeader {
            get {
                return ResourceManager.GetString("IpsSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Size (Hex).
        /// </summary>
        internal static string IpsSizeHexHeader {
            get {
                return ResourceManager.GetString("IpsSizeHexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Start.
        /// </summary>
        internal static string IpsStartHeader {
            get {
                return ResourceManager.GetString("IpsStartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length: {0:X} ({0}).
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln: {0}.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified: {0} bytes.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        internal static string Octal {
            get {
                return ResourceManager.GetString("Octal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Forum.
        /// </summary>
        internal static string OfficialForum {
            get {
                return ResourceManager.GetString("OfficialForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset:.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string OffsetHeader {
            get {
                return ResourceManager.GetString("OffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset: {0:X} ({0}).
        /// </summary>
        internal static string OffsetStatus {
            get {
                return ResourceManager.GetString("OffsetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches: {0}.
        /// </summary>
        internal static string Patches {
            get {
                return ResourceManager.GetString("Patches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch file size: {0} bytes.
        /// </summary>
        internal static string PatchFileSize {
            get {
                return ResourceManager.GetString("PatchFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row: {0} / {1} ({2} bytes).
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SizeHeader {
            get {
                return ResourceManager.GetString("SizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (Hex).
        /// </summary>
        internal static string SizeHexHeader {
            get {
                return ResourceManager.GetString("SizeHexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String View.
        /// </summary>
        internal static string StringView {
            get {
                return ResourceManager.GetString("StringView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string Toolbar {
            get {
                return ResourceManager.GetString("Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeHeader {
            get {
                return ResourceManager.GetString("TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
